jobs:
  - job: 'Test'
    pool:
      vmImage: 'ubuntu-18.04' 
    steps:
    - script: docker pull owasp/zap2docker-stable
      displayName: "pull Zap"
    - script: docker run -i owasp/zap2docker-stable zap-cli -v quick-scan --spider -l 'Low' -r -sc -o '-config api.disablekey=true' $(zapTargetUrl)
      continueOnError: true
      displayName: "Run ZAP Spider + Quick Scan"
  - job: 'Get_Results'
    dependsOn:
    - Test
    condition: succeeded('Test')
    steps:
    - script: echo this will run when Test runs and succeeds  
    # Azure file copy
    # Copy files to Azure Blob Storage or virtual machines
    #- task: AzureFileCopy@4
    #  inputs:
    #    sourcePath: 
    #    azureSubscription: 
    #    destination: # Options: azureBlob, azureVMs
    #    storage: 
        #containerName: # Required when destination == AzureBlob
        #blobPrefix: # Optional
        #resourceGroup: # Required when destination == AzureVMs
        #resourceFilteringMethod: 'machineNames' # Optional. Options: machineNames, tags
        #machineNames: # Optional
        #vmsAdminUserName: # Required when destination == AzureVMs
        #vmsAdminPassword: # Required when destination == AzureVMs
        #targetPath: # Required when destination == AzureVMs
        #additionalArgumentsForBlobCopy: # Optional
        #additionalArgumentsForVMCopy: # Optional
        #enableCopyPrerequisites: false # Optional
        #copyFilesInParallel: true # Optional
        #cleanTargetBeforeCopy: false # Optional
        #skipCACheck: true # Optional
        #sasTokenTimeOutInMinutes: # Optional